name: Deploy PDF to GitHub Pages

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-gh-pages:
    name: Deploy the PDF to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: registry.gitlab.com/islandoftex/images/texlive:TL2024-2025-01-05-medium@sha256:3c51378a5396fefbeb722c347450660e9a9b5539ffbfcf5da13df7c6a22cb0e3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v5  
    
    - name: Build PDF
      shell: bash
      run: |
        pdflatex verifasts-logic.tex
        bibtex verifasts-logic
        pdflatex verifasts-logic.tex
        pdflatex verifasts-logic.tex
        mkdir artifact
        cp verifasts-logic.pdf artifact

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: artifact
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
